#ifndef __PolyMathUIMyDialogSaveResult__
#define __PolyMathUIMyDialogSaveResult__

/**
@file
Subclass of MyDialogSaveResult, which is generated by wxFormBuilder.
*/

#include "../../fb/wxUIPM.h"

//// end generated include

/** Implementing MyDialogSaveResult */
class PolyMathUIMyDialogSaveResult : public MyDialogSaveResult
{
	protected:
		// Handlers for MyDialogSaveResult events.
		void SaveResultClick( wxCommandEvent& event );
		void CancelSaveResultClick( wxCommandEvent& event );
	public:
		/** Constructor */
		PolyMathUIMyDialogSaveResult( wxWindow* parent );
	//// end generated class members

};

#endif // __PolyMathUIMyDialogSaveResult__
