#ifndef __PolyMathUIframeMain__
#define __PolyMathUIframeMain__

/**
@file
Subclass of frameMain, which is generated by wxFormBuilder.
*/

#include "../../fb/wxUIPM.h"
#include "PolyMathUIframeTable.h"
#include "../../../Containers/Vector.h"
#include "../../../Tables/TableInterface.hpp"
#include "../../../Tables/LinearListTable.hpp"
#include "../../../Tables/AVLTreeTable.hpp"
#include "../../../Tables/LinearTableOnAnArray.hpp"
#include "../../../Tables/ListHashTable.hpp"
#include "../../../Tables/OpenHashTable.hpp"
#include "../../../Tables/OrderedTableOnAnArray.hpp"
//// end generated include

/** Implementing frameMain */
class PolyMathUIframeMain : public frameMain
{
	enum SelectedTable
	{
		Table_LinearTableOnAnArray = 0,
		Table_LinearListTable,
		Table_OrderedTable,
		Table_OpenHashTable,
		Table_ListHashTable,
		Table_AVLTreeTable
	};
	
protected:
	SelectedTable selectedTable;
	ad::Vector<TableInterface<std::string, Polynomial>*> tables;
	ad::Vector<PolyMathUIframeTable*> tablesUI;
	// Handlers for frameMain events.
	void OpenMenuSelected( wxCommandEvent& event );
	void SaveMenuSelected( wxCommandEvent& event );
	void SaveAsMenuSelected( wxCommandEvent& event );
	void m_menuItem_lin_arr_selected( wxCommandEvent& event );
	void m_menuItem_lin_list_selected( wxCommandEvent& event );
	void m_menuItem_order_arr_selected( wxCommandEvent& event );
	void m_menuItem_open_hash_selected( wxCommandEvent& event );
	void m_menuItem_hash_chain_selected( wxCommandEvent& event );
	void m_menuItem_avl_selected( wxCommandEvent& event );
	void TextUpdated( wxCommandEvent& event );
	void CalculateClick( wxCommandEvent& event );
	void MainSaveClick( wxCommandEvent& event );
public:
	/** Constructor */
	PolyMathUIframeMain( wxWindow* parent );
//// end generated class members

};

#endif // __PolyMathUIframeMain__
