#ifndef __PolyMathUIMyDialogDelete__
#define __PolyMathUIMyDialogDelete__

/**
@file
Subclass of MyDialogDelete, which is generated by wxFormBuilder.
*/

#include "../../fb/wxUIPM.h"

//// end generated include

/** Implementing MyDialogDelete */
class PolyMathUIMyDialogDelete : public MyDialogDelete
{
	protected:
		// Handlers for MyDialogDelete events.
		void DeleteDialogButtonClick( wxCommandEvent& event );
		void CancelDialogButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		PolyMathUIMyDialogDelete( wxWindow* parent );
	//// end generated class members

};

#endif // __PolyMathUIMyDialogDelete__
