#ifndef __PolyMathUIMyDialogRename__
#define __PolyMathUIMyDialogRename__

/**
@file
Subclass of MyDialogRename, which is generated by wxFormBuilder.
*/

#include "../../fb/wxUIPM.h"

//// end generated include

/** Implementing MyDialogRename */
class PolyMathUIMyDialogRename : public MyDialogRename
{
	protected:
		// Handlers for MyDialogRename events.
		void RenameDialogButtonClick( wxCommandEvent& event );
		void CancelDialogButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		PolyMathUIMyDialogRename( wxWindow* parent );
	//// end generated class members

};

#endif // __PolyMathUIMyDialogRename__
