#ifndef __PolyMathUIMyDialogAdd__
#define __PolyMathUIMyDialogAdd__

/**
@file
Subclass of MyDialogAdd, which is generated by wxFormBuilder.
*/

#include "../../fb/wxUIPM.h"

//// end generated include

/** Implementing MyDialogAdd */
class PolyMathUIMyDialogAdd : public MyDialogAdd
{
	protected:
		// Handlers for MyDialogAdd events.
		void AddDialogButtonClick( wxCommandEvent& event );
		void CancelDialogButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		PolyMathUIMyDialogAdd( wxWindow* parent );
	//// end generated class members

};

#endif // __PolyMathUIMyDialogAdd__
