#ifndef __PolyMathUIframeTable__
#define __PolyMathUIframeTable__

/**
@file
Subclass of frameTable, which is generated by wxFormBuilder.
*/

#include "../../fb/wxUIPM.h"

//// end generated include

/** Implementing frameTable */
class PolyMathUIframeTable : public frameTable
{
	protected:
		// Handlers for frameTable events.
		void tableClosed(wxCloseEvent& event);
		void ClearTableClick( wxCommandEvent& event );
		void AddItemClick( wxCommandEvent& event );
		void RenameItemClick( wxCommandEvent& event );
		void DeleteItemClick( wxCommandEvent& event );
	public:
		/** Constructor */
		PolyMathUIframeTable( wxWindow* parent );
	//// end generated class members

};

#endif // __PolyMathUIframeTable__
